### ISSUE TITLE
DB schema User

### ISSUE THREAD

**Issue by andrelandgraf** [andrelandgraf/high5-learning-backend#10]
This has to be done before we can talk about schemas for the teacher and the student. I am currently thinking about subclasses like Teacher extends User, Student extends User. The other option would be to merge Teacher and Student together into User, or somehow connect them like:

```
Teacher: {
    (for other attributes see issue DB schema Teacher)
     user: User
}

Student: {
    (for other attributes see issue DB schema Student)
     user: User
}
```

**Comment by andreweinkoetz** [comment]
So there are two different approaches (in my opinion):
Extending the user schema
```
User: {
   username: string
   password: string 
   userType: Teacher/Student
}
```
Storing all values in the "detailed tables"
```
Teacher: {
  (values as shown in DB schema teacher issue)
   username: string
   password: string
}
```
In general i think it's easier to simply store the different usertypes in different tables as we will have to match them to different tables (students -> exercises, homework, partClass) (teachers -> assignedClasses)

**Comment by andreweinkoetz** [comment]
Solution: Prefering User only table with usertype and myclasses[]
