### ISSUE TITLE
Submission Controller & Routes

### ISSUE THREAD

**Issue by andrelandgraf** [andrelandgraf/high5-learning-backend#20]
Implementing the controller and the route of the submission model.

**Comment by andrelandgraf** [comment]
Added create function and you already implemented the list by homework function. The submission controller should be done. Testing needed next.

**Comment by ghost** [comment]
I will add soon some testing to this function

**Comment by andrelandgraf** [comment]
See #21 for the statistics (also part of submission controller but we have a separate issue for statistics).
