### ISSUE TITLE
#21 implement map reduce for submissions -> statistics

### ISSUE THREAD

**Issue by HmG248** [andrelandgraf/high5-learning-backend#21]

**Comment by andrelandgraf** [comment]
Get Submission for Homework should not only return the plain submissions of all students to the teacher but a statistic. 

This will include:

{
  count: number //sum of submissions for this homework
  studentCount: number //number of students that are member of the class, teachers not included
  submissionRate: number // (count / studentCount) 
  submissions: [] // array of submissions, see #9 and #12 
  homework: HomeworkModel //array of exercises of the homework included
  exerciseStatistics: [
            // for each exercise of the homework one item in the list
            statistics {
                     pickedAnswers: [_, _, _, _]  //count of how many students submissed what answer.
                     answerPercentage: [_, _,_,_] //same as percentage
                     rightAnswerPicked // count of how many students picked the right answer
                     rightAnswerPercentage // same as percentage
            }
 ]
}

**Comment by andrelandgraf** [comment]
Implemented: example:
`{
count: 2,
submissions: [
{
exercises: [
0,
2,
3
],
_id: "5b127516fb08fd165c80b8fb",
student: "5b0acb074568f120f47e601c",
homework: "5b12737cfb08fd165c80b8fa"
},
{
exercises: [
0,
2,
1
],
_id: "5b12759afb08fd165c80b8fe",
homework: "5b12737cfb08fd165c80b8fa",
student: "5b12486a1f4af62ac4534bcf"
}
],
homework: {
_id: "5b12737cfb08fd165c80b8fa",
title: "Hausaufgabe 1",
exercises: [
{
answers: [
"a",
"b",
"c",
"d"
],
question: "Frage 1",
rightSolution: 0
},
{
answers: [
"e",
"f",
"g",
"h"
],
question: "Frage 2",
rightSolution: 1
},
{
answers: [
"i",
"j",
"k",
"l"
],
question: "Frage 3",
rightSolution: 3
}
]
},
exerciseStatistics: [
{
pickedAnswers: [
2,
0,
0,
0
],
answerPercentage: [
1,
0,
0,
0
],
rightAnswerPicked: 2,
rightAnswerPercentage: 1
},
{
pickedAnswers: [
0,
0,
2,
0
],
answerPercentage: [
0,
0,
1,
0
],
rightAnswerPicked: 0,
rightAnswerPercentage: 0
},
{
pickedAnswers: [
0,
1,
0,
1
],
answerPercentage: [
0,
0.5,
0,
0.5
],
rightAnswerPicked: 1,
rightAnswerPercentage: 0.5
}
],
studentCount: 2,
submissionRate: 1
}`

**Comment by andrelandgraf** [comment]
I just refactored map reduce and the statistics. I still have one open issue / bug. Map Reduce still wont work if only one student has submitted the homework. 

I cannot figure out why mapreduce misbehaves in that way and therefore I asked at stackoverflow.
See: https://stackoverflow.com/questions/50787093/mongoose-map-reduce-returns-wrong-result-when-input-is-one

If mapreduce just does not work for one submission, I have to implement an if case and fill the statistics by hand. But lets wait for an answer at stackoverflow first.
