### ISSUE TITLE
No password required to register

### ISSUE THREAD

**Issue by andreweinkoetz** [andrelandgraf/high5-learning-backend#22]
In contrast to our specification, it is possible to sign up using no password:

![image](https://user-images.githubusercontent.com/14924669/40885654-0b5eb4b0-672b-11e8-9268-83c71cd818ab.png)

-->

![image](https://user-images.githubusercontent.com/14924669/40885672-295635a6-672b-11e8-8527-7af50b54cfbe.png)

Found during testing of the error handling --> please fix ❤️ 

EDIT: same behaviour for teacher

**Comment by andrelandgraf** [comment]
Yeah I have not implemented form checks yet :-) will do!

**Comment by andrelandgraf** [comment]
Done in frontend
