### ISSUE TITLE
Store school of a user in token

### ISSUE THREAD

**Issue by andreweinkoetz** [andrelandgraf/high5-learning-backend#25]
As I mentioned before:
I would appreciate to have the school to which a user belongs, stored in the JWtoken in order to easily use this as a param to get all students belonging to the same school (or other methods.)

**Comment by andrelandgraf** [comment]
You can now access the school`s name via token.schoolname as you would with user id, type and name. Schools name is a unique field so you can use the schoolname as a identifier for the school.

**Comment by andreweinkoetz** [comment]
Please see last commit. Login is now working but storing token when registering will not include the schoolname.
