### ISSUE TITLE
Username not unqiue

### ISSUE THREAD

**Issue by andreweinkoetz** [andrelandgraf/high5-learning-backend#26]
The username of a student or teacher has to be unique because we need to separate them precisely. 

Current behaviour: Backend does not check if username already exists. User model does not specify the username as unique. 

Expected behaviour: no duplicates

Not necessary, but i would like it: use and validate email as username (because these are always unique)

**Comment by andrelandgraf** [comment]
Username is of type email now (validation in frontend) and unquie (validaiton in backend)
