### ISSUE TITLE
User cannot change his password

### ISSUE THREAD

**Issue by andreweinkoetz** [andrelandgraf/high5-learning-backend#29]
After the recent changes, a user cannot change his password as the backend is not able to process the request:

![image](https://user-images.githubusercontent.com/14924669/41199405-a66bb7f8-6c91-11e8-94ca-5a0fa394523f.png)

**Comment by andrelandgraf** [comment]
I will fix this. I had to rewrite the change password function, so this is my issue :-) thanks for letting me know.

**Comment by andrelandgraf** [comment]
Fixed.
