### ISSUE TITLE
When adding exercises to a homework, an error appears

### ISSUE THREAD

**Issue by HmG248** [andrelandgraf/high5-learning-backend#31]
This error appears when adding an exercise to a homework:
![screen shot 2018-06-10 at 17 50 38](https://user-images.githubusercontent.com/38717594/41203421-d9b80d92-6cd6-11e8-8ba9-f349abde18a7.png)
I'm pretty sure this comes from this:
![screen shot 2018-06-10 at 17 52 08](https://user-images.githubusercontent.com/38717594/41203429-0ac256b8-6cd7-11e8-8a35-2da794a20be2.png)
Could you take a look into that, as you added this? I failed to understand the purpose of the code :sim

**Comment by andreweinkoetz** [comment]
Why is this a backend issue?
The code you posted is from ModalClassNewDialog - but the error occurs when adding an exercise, which is done in ModalDialogNewHomework res. CreateExercise (none of them have i ever touched 😄 ) as you can see in the error log.

**Comment by andreweinkoetz** [comment]
Just FYI: The code you posted is just for rendering the suggestions for the add students to class field in ModalAddNewClass

**Comment by HmG248** [comment]
fixed
