### ISSUE TITLE
When logging in as a student and you don't have any classes, backend crashes

### ISSUE THREAD

**Issue by HmG248** [andrelandgraf/high5-learning-backend#34]
this is the error you get at the backend: 
![screen shot 2018-06-11 at 11 50 20](https://user-images.githubusercontent.com/38717594/41224827-aad78a38-6d6d-11e8-8449-adf3c46d65cd.png)

**Comment by andrelandgraf** [comment]
This has not yet happened to me. This has probably something todo with @ge98hod?

**Comment by HmG248** [comment]
You tried it right now after updating everything? The error only occurs after updating everything. I already find the source of the error, it is the findOpenHomework function in the class controller, it doesn't work when you don't have any classes

**Comment by HmG248** [comment]
@tum-aweink  The error comes definitely from the function findOpenHomework, it only works when you have at least one class. Additionally, when you don't have any homework, the badge doesn't work as props.openHomework in the frontend is undefined.

**Comment by andreweinkoetz** [comment]
This is my method. I see the problem and havent thought about it. I will correct it soon

**Comment by andreweinkoetz** [comment]
see https://github.com/tum-aweink/high5-learning-frontend/commit/0e1d9c714e567d4bba4aa79fdca3006163da5c8b
