### ISSUE TITLE
data for submission chart

### ISSUE THREAD

**Issue by ghost** [andrelandgraf/high5-learning-backend#37]
We need for the submission line chart data like this:

 const data = [
            {date: '2018-05-01', num: 4, students: [username1, username2, username3]},
            {date: '2018-05-02', num: 6, students: [username1]},
            {date: '2018-05-03', num: 1, students: [username1, username2]},
            {date: '2018-05-04', num: 10, students: [username1, username2]},
        ];

Thx!

**Comment by ghost** [comment]
Very very nice!

Can you return the student's name instead of id - than it's it!

<img width="418" alt="bildschirmfoto 2018-06-13 um 07 56 20" src="https://user-images.githubusercontent.com/39064712/41332729-5fa3f2ea-6edf-11e8-9777-e71f75173ba9.png">

**Comment by andrelandgraf** [comment]
Did it! 
Students is now an array of username and _id of users. 

`aggregatedSubmissions: [
{
_id: {
date: "2018-06-12"
},
students: [
{
_id: "5b1d6fab46fb3e098050bb54",
username: "andre2.student@web.de"
},
{
_id: "5b1ff085d9a5a306245cb72c",
username: "andre3.student@web.de"
}
],
count: 2
},
{
_id: {
date: "2018-06-10"
},
students: [
{
_id: "5b1d560252467016006d2b72",
username: "andre.student@web.de"
}
],
count: 1
}
],`
