### ISSUE TITLE
DB schema: homework with exercises

### ISSUE THREAD

**Issue by ghost** [andrelandgraf/high5-learning-backend#4]
Discussion of Schema to represent homework with exercises.

**Comment by tum-aweink** [comment]
Suggestion 1:
class = {
id: number
title: string
description: string
creator: Teacher
participants: student[]
}

**Comment by andreweinkoetz** [comment]
Suggestion 1:
homework = {
id: number
title: string
exercises: exercise[]
assignedClass: Class
}

**Comment by andreweinkoetz** [comment]
Suggestion 1:
exercise = {
id: number
assignedHomework: Homework
answerPossibilities: string[]
solution: int
}

**Comment by ghost** [comment]
Suggestion2:

Exercise = {
id: number
question: string
choice1: string
choice2: string
choice3: string
choice4: string
solution: integer
}

Do we need a link from Exercise to Homework?

**Comment by HmG248** [comment]
(probably final): Suggestion
homework = {
title: string
exercises: [
id: string
question: string
answers: string[]
rightSolution: number
]
assignedClass: class
}

I added id: string to exercises, because with this it is easier to differentiate the exercises and you can instantly see, which number the exercise has

**Comment by andrelandgraf** [comment]
This is not necessarily needed as we have the index of the array already as an id. You could use the index say in the front-end to identify the exercises and access them. Furthermore why string? How would you want to generate a string id?

**Comment by HmG248** [comment]
A exercise in every homework has a string id, which starts with "1" and ends with the number of exercises. This is done, so that a exercise in every homework has a unique id, which I 1) need so that the .map function doesn't complain and 2) so that I can differentiate between the different exercises, as each exercise is a single component and I need to know for which exercise something happened like changing the title.

**Comment by andrelandgraf** [comment]
Alright, then I will copy that for the submission model to connect it to its homeworks exercises. But why don't you just use type number for numbers?

**Comment by HmG248** [comment]
No particular reason, it does make more sense to me, because it is an id and not a number with which you should calculate something. But I can switch that to number if you want, that's not that big of a deal.

**Comment by andreweinkoetz** [comment]
If we stick to this approach i would recommend that we store the exercises separate from the homework, i.e. as a new model ‚exercise‘. There you would be provided with a generated id (of type string) by mongodb - and if sth is worth having an id it should probably deserve it‘s own table. The array of exercises in homework will then contain the ids pointing to the entries in the other table. Additionally we could reference those exercises in the submission model.

**Comment by HmG248** [comment]
I created the id for the exercises so that I have a reference point for each exercise (as each one is a seperate component) and I know in which exercise exactly something changed and I can easily identify the corresponding data for a exercise in the state. Technically speaking, it would probably also be possible to do it without an id, even though I think it would be some work, but it would probably be possible. The id is only there for having a reference to each exercise. If you want, I can delete the id of the exercises from the homework information which is send to the DB. In the DB, we still have the index of the array as an id.

**Comment by andreweinkoetz** [comment]
I see your point and if you need to identify a single exercise then having an id is mandatory. My idea was simply to store the exercises separately from the homework e.g. my models would look like this:
Homework:
```
const HomeworkSchema = new mongoose.Schema({
    title: {
        type: String,
        required: true
    },
   exercises: [{
        type: mongoose.Schema.Types.ObjectId
        ref: 'Exercise'
}],
    assignedClass: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Class'
    }
},{ collection: 'homework' });
```

And for exercise (note that id is assigned automatically):
```
const ExerciseSchema = new mongoose.Schema({
        question: {
            type: String,
            required: true
        },
        answers: {
            type: [String],
            required: true
        },
        rightSolution: {
            type: Number,
            required: true
        }
  },{ collection: 'exercise' });
```

**Comment by HmG248** [comment]
We can of course do that, too, but I wonder what's the advantage of this approach compared to how we do it now? Also, should I then delete id for each exercise before sending the data to the backend?

**Comment by andrelandgraf** [comment]
Sorry that I have to ask again, I just talked with Martin about this and I still see no need to change the model. "Exercises" is an array of key value pairs assigned to this exercise. Every exercise has an ID already. That is the very index of the key value map inside the exercise array. 

First of all: **index is a number**. 
Making your manual id you are proposing a string makes things even more complicated as you cannot use the string to access your exercise of choice within the array using the string id (without a cast). 
Second: **index starts with zero**.
@HmG248 you said the id will start with one. That is not intuitive. You cannot use the id to access your exercise of choice within the array using the string id (without id--; the value).

So accessing an exercise with this id is not intuitive and not practical. I really understand that you need an id in the frontend when mapping / splitting exercises in different components. I would suggest you use the index in your front end as the identifier. It is a number and starts from zero to array.length -1. You will receive an array of exercises from the backend nevertheless and the index is the key of choice in that sense.

About the map function: use array.indexOf(element) to receive the id. 

@tum-aweink about your solution that goes even one step further. I really see your point but it would make it way harder to access all the relevant data in a query. Just think about the statistics. You would need to retrieve the right homework, access the list of exercise models of this homework, and access the submission model. Moreover, right now, the submission model and the exercise array inside the homework are every analogue to each other. Changing the data schema would also hurt the simplicity between submission <-> exercises. 

If you guys really need an id apart from the index and I do not see your point, please let us discuss this in person as I really do struggle to understand your arguments in the sense that I think your solutions will mean more work and abstraction for all of us. If I am wrong with that, I will obviously let the old model go, but as I said, then lets find the solution in person.

**Comment by andreweinkoetz** [comment]
My proposal should only be considered **if** we really need an id. Personally, i don't see the necessity of an id. @HmG248 has to clarify why he can not simply use the [index from the map-function](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Array/map).

**Comment by HmG248** [comment]
So, the thing is, I already implemented the whole functionality of the modal dialog for creating a homework with this id. But as I said, this id was just something for me in the frontend, as I personally found it most intuitive (exercise 1 has id "1" etc.). We can discuss whether I should have implemented the id as a number, as this doesn't matter to me. But as I also already said, I can just delete the id before sending the data to the backend and you will have exactly the schema as in the backend. If you insist, I can of course delete the id completely and change my (whole) code. But we would have the same functionality and same outcome with more work as if I just delete the id before sending it to the backend.

**Comment by andreweinkoetz** [comment]
@andrelandgraf just FYI: check out [this](http://mongoosejs.com/docs/populate.html) reference doc. Using the id as refs enables you to get **all** subdocuments of a model with one simple query. So thinking about the statistics: All you need is the id of the homework - everything else you can achieve simply using `.populate('exercise')` - the more you know 😃

**Comment by andrelandgraf** [comment]
Wow, that's pretty neat!

**Comment by andrelandgraf** [comment]
@HmG284 this is not about you having to refactor all of your achievements. That's just about clarifying what we do out of what reasons. We discuss this tomorrow as a group and we will surely find a solution that fits everyone. 

Also the thing is, you changed a behaviour we discussed and closed the issue without asking if we would have more work, before you started doing so.
