### ISSUE TITLE
100% correct answers when no submission exists

### ISSUE THREAD

**Issue by HmG248** [andrelandgraf/high5-learning-backend#42]
When you don't have a single submission for a homework, the statistics show 100% correct answers

**Comment by andrelandgraf** [comment]
This was a frontend decision. @ge98hod implemented that because it is technically not wrong (0 of 0 is 100%) and it sounds way more positive than 0%. 

But sure, it may also look pretty unintuitive in the first place.

**Comment by HmG248** [comment]
Alright, I didn't know that, then let's just let it stay that way :)
