### ISSUE TITLE
DB schema: submission

### ISSUE THREAD

**Issue by andreweinkoetz** [andrelandgraf/high5-learning-backend#9]
Discussion of db schema for solutions (required attributes, links to related "tables")

**Comment by andreweinkoetz** [comment]
Suggestion 1:
solution = {
id: number
student: Student
exercise: Exercise
answers: int[] // UPDATE: answer: int
}

**Comment by andrelandgraf** [comment]
So exercise must be a list of exercises, right? As answers is a list of answers?

**Comment by andreweinkoetz** [comment]
I thought of a single solution for one exercise. Therefore "answers" should be answer:int

**Comment by ghost** [comment]
const SubmissionSchema = new mongoose.Schema({
    exercises:  {
        **type: [String],**
        enum: [0, 1, 2, 3],
        required: true
    },
    homework: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Homework',
        required: true
    },
    student: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
    }
},{ collection: 'submission' });

I have changed the data type for the exercises to a string array as a number array is not possible with the use of enums.

**Comment by andrelandgraf** [comment]
I reopened this issue as we still have a discussion about homework data model going on and the submission model does rely on the homework model.

**Comment by andrelandgraf** [comment]
const SubmissionSchema = new mongoose.Schema({
exercises: {
**type: [Number],**
~~enum: [0, 1, 2, 3],~~
required: true
},
homework: {
type: mongoose.Schema.Types.ObjectId,
ref: 'Homework',
required: true
},
student: {
type: mongoose.Schema.Types.ObjectId,
ref: 'User',
required: true
}
},{ collection: 'submission' });

Talked with @ge98hod about this change. The right answer in homework model is a number right now so we want to have a number here as well. This allows us to compare the chosen answer of the student and the right answer as it is saved in the homework model.
